rotateDeg1: -1.0471975511965976
rotateDeg2: -2.0943951023931953
rotateDeg3: -3.141592653589793
rotateDeg4: 2.0943951023931953
rotateDeg5: 1.0471975511965976

# https://blog.csdn.net/hanmoge/article/details/122441695
# https://developer.aliyun.com/article/1012198
# focal_length = width_ / (2.0 * tan(HFOV/2.0))
#
# AVP-SLAM-ws/src/AVP-SLAM/simlate_gazebo/simulate_robot/urdf/robot_with_realsense.urdf.xacro
# <!-- 75x65 degree FOV for the depth sensor -->
# <horizontal_fov>1.5184351666666667</horizontal_fov>
# <vertical_fov>1.0122901111111111</vertical_fov>
# <width>640</width>
# <height>480</height>
#
# focal_x = width_ / (2.0 * tan(HFOV/2.0)) = 640/(2 * math.tan(1.5184351666666667/2)) = 337.21007317816117
# TODO: qiuzc, focal_y is not ok ?
# focal_y = height_ / (2.0 * tan(VFOV/2.0)) = 480/(2 * math.tan(1.0122901111111111/2)) = 432.9718978095195
K: [337.2084410968044, 0.0, 320.5,
    0.0, 337.2084410968044, 240.5,
    0.0, 0.0, 1.0]
R0: [0.0, 1.0, 0.0,
    0.0, 0.0, 1.0,
    1.0, 0.0, 0.0]
T0: [0.0, 0.5, 0.0]
imageRowIncrease: 2
imageColIncrease: 4
cameraRealiableDis: 8
skyColor: 179
pointCloudLeafSize: 0.1
farPointThresh: 20
closePointThresh: 0.1

mapSave: true
# maybe jacklee should change this to your own path
mapSaveLocation: "/media/psf/aqiuxx/slam/slam_data/avp/avp_slam_plus/laserCloudMap.pcd"
odomKeyFramDisThresh: 1.0
InvalidColorThresh: 60
# ICP
useICP: false
IcpMaxCorrespondenceDistance: 20
IcpMaximumIterations: 100
IcpTransformationEpsilon: 1e-10
IcpEuclideanFitnessEpsilon: 0.001
icpFitnessScoreThresh: 0.3
# NDT
useNDT: true
ndtTransformationEpsilon: 0.01
ndtResolution: 1.0
ndtFitnessScoreThresh: 0.3

# for adding noise in Gazebo
gazebo_c1: 0.001
gazebo_c2: 0.001
gazebo_c3: 0.001
gazebo_c4: 0.001

# for adding noise in Odometry
odom_c1: 0.001
odom_c2: 0.001
odom_c3: 0.001
odom_c4: 0.001

# hand tuning covariance for odometry edge
odom_cov: [0.03, 0.0, 0.0,
           0.0, 0.03, 0.0,
           0.0, 0.0, 0.01]
